name: Linting

on:
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    container: yoheimuta/protolint:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run protolint
        run: protolint proto/*.proto
