name: Release
on:
    push:
        tags: ["v*.*.*"]

jobs:
    publish-npm-package:
        name: Publish NPM Package
        runs-on: ubuntu-latest
        if: github.ref_type == 'tag'
        permissions:
            id-token: write # Required for OIDC
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: cd npm-package && npm i

            - name: Copy documents to package directory
              run: cp README.md LICENSE CHANGELOG.md ./npm-package/

            - name: Publish to NPM
              run: cd npm-package && npm publish --access public

    release:
        name: Release
        if: github.ref_type == 'tag'
        permissions:
            contents: write
        uses: SE-UUlm/snowballr-ci/.github/workflows/release.yml@v1
