name: Release
on:
    push:
        tags: ["v*.*.*"]
        branches: ["releases/v*.*.*"]

jobs:
    publish-npm-package:
        name: Publish NPM Package${{ github.ref_type == 'tag' && '' || ' (dry-run)' }}
        runs-on: ubuntu-latest
        permissions:
            id-token: write # Required for OIDC
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies and build package
              run: cd npm-package && npm i && npm run compile

            - name: Verify that package content exists
              run: ls -la npm-package/dist | grep -E ".ts"

            - name: Copy documents to package directory
              run: cp README.md LICENSE CHANGELOG.md ./npm-package/

            - name: Publish to NPM
              run: cd npm-package && npm publish --access public${{ github.ref_type == 'tag' && '' || ' --dry-run' }}

    release:
        name: Release
        if: github.ref_type == 'tag'
        permissions:
            contents: write
        uses: SE-UUlm/snowballr-ci/.github/workflows/release.yml@v1
